In [1]:
import pandas as pd

In [6]:
df=pd.read_csv('/content/sample_data/train.csv')

In [7]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [8]:
df=df.dropna()

In [9]:
x=df.drop('label',axis=1)

In [10]:
y=df['label']

In [11]:
x.shape

(18285, 4)

In [12]:
y.shape

(18285,)

In [13]:
import tensorflow as tf

In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [15]:
#vocabulary size
voc_size=5000

In [16]:
#one hot representation
messages=x.copy()

In [17]:
messages.reset_index(inplace=True)

In [18]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [22]:
messages['title'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [24]:
import nltk

In [23]:
nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> all


       | 
       | Downloading package abc to /root/nltk_data...
       |   Unzipping corpora/abc.zip.
       | Downloading package alpino to /root/nltk_data...
       |   Unzipping corpora/alpino.zip.
       | Downloading package averaged_perceptron_tagger to
       |     /root/nltk_data...
       |   Unzipping taggers/averaged_perceptron_tagger.zip.
       | Downloading package averaged_perceptron_tagger_ru to
       |     /root/nltk_data...
       |   Unzipping taggers/averaged_perceptron_tagger_ru.zip.
       | Downloading package basque_grammars to /root/nltk_data...
       |   Unzipping grammars/basque_grammars.zip.
       | Downloading package bcp47 to /root/nltk_data...
       | Downloading package biocreative_ppi to /root/nltk_data...
       |   Unzipping corpora/biocreative_ppi.zip.
       | Downloading package bllip_wsj_no_aux to /root/nltk_data...
       |   Unzipping models/bllip_wsj_no_aux.zip.
       | Downloading package book_grammars to /root/nltk_data...
       |   Un


---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q


True

In [19]:
import nltk
import re
from nltk.corpus import stopwords

In [20]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [25]:
#Data Preprocessing
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
from nltk.stem import WordNetLemmatizer
wordnet=WordNetLemmatizer()
corpus=[]
for i in range(len(messages)):
  print(i)
  review=re.sub('[^a-zA-Z]',' ',messages['title'][i])
  #print(review)
  review=review.lower()
  #print(review)
  review=review.split()
  #print(review)
  review=[wordnet.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
  print(review)
  review=' '.join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
15785
['speaker', 'ryan', 'obamacare', 'lite', 'plan', 'primer', 'breitbart']
15786
['choice', 'trump', 'oligarchy']
15787
['paul', 'ryan', 'call', 'fact', 'comey', 'memo', 'people', 'want', 'hurt', 'president']
15788
['anti', 'trump', 'protester', 'tool', 'oligarchy']
15789
['next', 'big', 'shoe', 'drop']
15790
['protester', 'going', 'trump', 'hotel', 'dc', 'communist', 'lunatic', 'course']
15791
['way', 'older', 'people', 'naturally', 'improve', 'health', 'wellness']
15792
['watch', 'gunfire', 'rattle', 'tehran', 'drone', 'buzz', 'iranian', 'capital']
15793
['question', 'going', 'need', 'ask', 'investment', 'fee', 'new', 'york', 'time']
15794
['lawsuit', 'claim', 'san', 'francisco', 'state', 'university', 'exhibit', 'pattern', 'anti', 'jewish', 'animus']
15795
['occupier', 'david', 'fry', 'released', 'jail', 'really', 'free']
15796
['wikileaks', 'assange', 'promise', 'hillary', 'arrest', 'next', 'release']
15797
['heal', 'chakras', '

In [26]:
corpus

['house dem aide even see comey letter jason chaffetz tweeted',
 'flynn hillary clinton big woman campus breitbart',
 'truth might get fired',
 'civilian killed single u airstrike identified',
 'iranian woman jailed fictional unpublished story woman stoned death adultery',
 'jackie mason hollywood would love trump bombed north korea lack trans bathroom exclusive video breitbart',
 'beno hamon win french socialist party presidential nomination new york time',
 'back channel plan ukraine russia courtesy trump associate new york time',
 'obama organizing action partner soros linked indivisible disrupt trump agenda',
 'bbc comedy sketch real housewife isi cause outrage',
 'russian researcher discover secret nazi military base treasure hunter arctic photo',
 'u official see link trump russia',
 'yes paid government troll social medium blog forum website',
 'major league soccer argentine find home success new york time',
 'well fargo chief abruptly step new york time',
 'anonymous donor pay 

In [27]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[4970, 150, 203, 2642, 1527, 3291, 3238, 4917, 1859, 2426],
 [4249, 2138, 2109, 2014, 2948, 2244, 669],
 [599, 3210, 2517, 785],
 [2616, 3606, 4012, 4878, 2575, 2717],
 [3801, 2948, 3455, 2332, 3144, 1159, 2948, 4398, 3780, 814],
 [2411,
  2523,
  2831,
  2291,
  2908,
  277,
  187,
  1290,
  1049,
  2961,
  2570,
  1461,
  3200,
  3999,
  669],
 [1512, 4970, 2007, 4484, 1585, 3374, 1834, 4239, 1452, 1722, 375],
 [2047, 3224, 2560, 2138, 2662, 1834, 277, 1291, 1452, 1722, 375],
 [2810, 4282, 693, 4857, 2410, 1271, 3659, 2926, 277, 2897],
 [2164, 2641, 4877, 269, 4554, 4187, 3881, 3732],
 [2093, 446, 4025, 3387, 617, 2156, 1199, 2574, 3261, 24, 3608],
 [4878, 4380, 1527, 4315, 277, 2662],
 [3291, 2519, 3571, 278, 1418, 3021, 1040, 1957, 1361],
 [2167, 234, 4402, 53, 4388, 4654, 1096, 1452, 1722, 375],
 [3110, 579, 1684, 4991, 3396, 1452, 1722, 375],
 [4440, 142, 2421, 3002, 4254, 3810, 4878, 4756, 3055, 3517],
 [3083, 362, 2138],
 [2118, 1037, 3006, 3013, 277, 443, 4006, 669],
 [3657, 

In [28]:
#Embedding Reprentation
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4917 1859 2426]
 [   0    0    0 ... 2948 2244  669]
 [   0    0    0 ... 3210 2517  785]
 ...
 [   0    0    0 ... 1452 1722  375]
 [   0    0    0 ... 2326 4622 2504]
 [   0    0    0 ... 2115  266 3238]]


In [29]:
len(embedded_docs)

18285

In [30]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 4970,
        150,  203, 2642, 1527, 3291, 3238, 4917, 1859, 2426], dtype=int32)

In [31]:
#Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [32]:
import numpy as np
x_final=np.array(embedded_docs)
y_final=np.array(y)

In [33]:
x_final.shape,y_final.shape

((18285, 20), (18285,))

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_final,y_final,test_size=0.33,random_state=42)

In [36]:
x_train.shape

(12250, 20)

In [35]:
#Model training
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 25s 89ms/step - loss: 0.3397 - accuracy: 0.8380 - val_loss: 0.1926 - val_accuracy: 0.9165
Epoch 2/10
192/192 [==============================] - 4s 19ms/step - loss: 0.1302 - accuracy: 0.9485 - val_loss: 0.2143 - val_accuracy: 0.9203
Epoch 3/10
192/192 [==============================] - 3s 17ms/step - loss: 0.0831 - accuracy: 0.9700 - val_loss: 0.2152 - val_accuracy: 0.9185
Epoch 4/10
192/192 [==============================] - 2s 12ms/step - loss: 0.0481 - accuracy: 0.9851 - val_loss: 0.2466 - val_accuracy: 0.9138
Epoch 5/10
192/192 [==============================] - 3s 16ms/step - loss: 0.0276 - accuracy: 0.9918 - val_loss: 0.2752 - val_accuracy: 0.9152
Epoch 6/10
192/192 [==============================] - 2s 10ms/step - loss: 0.0187 - accuracy: 0.9944 - val_loss: 0.3803 - val_accuracy: 0.9167
Epoch 7/10
192/192 [==============================] - 3s 14ms/step - loss: 0.0085 - accuracy: 0.9984 - val_loss: 0.4555 - val_accuracy: 0.912

In [38]:
#Performance Metrics and accuracy
y_pred=model.predict(x_test)

189/189 [==============================] - 1s 3ms/step


In [39]:
from sklearn.metrics import confusion_matrix

In [45]:
y_test

array([1, 0, 0, ..., 0, 1, 1])

In [46]:
y_pred

array([[9.9999893e-01],
       [1.0472816e-04],
       [1.1447519e-04],
       ...,
       [4.3338165e-04],
       [9.9792993e-01],
       [9.9999547e-01]], dtype=float32)

In [47]:
threshold = 0.5
y_pred_class = np.where(y_pred >= threshold, 1, 0)

In [48]:
confusion_matrix(y_test,y_pred_class)

array([[3106,  313],
       [ 210, 2406]])

In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_class)

0.9133388566694284